name: Debug CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          install_url: https://releases.nixos.org/nix/nix-2.24.1/install
      - uses: cachix/cachix-action@v15
        with:
          name: veridise-private
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          pushFilter: '(-source$)'
      - run: mkdir -p xunit-reports
      - name: Build with GCC
        run: nix --print-build-logs build '.#debugGCC'
      - name: Copy xUnit report for GCC
        run: cp result/artifacts/gcc-report.xml xunit-reports
      - name: Build with Clang
        run: nix --print-build-logs build '.#debugClangCov'
      - name: Copy xUnit report for clang
        run: cp result/artifacts/clang-report.xml xunit-reports
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: xunit-reports/*-report.xml

