on:
  pull_request:
    types: ['closed']
    branches: [ main ]


name: Transition Issue to Done

jobs:
  call-workflow:
    uses: Veridise/.github/.github/workflows/jira-finished-transition-core.yml@main
    with:
      head-ref: ${{ github.head_ref }}
      merged: ${{ github.event.pull_request.merged }}
    secrets: inherit
