on:
  pull_request_review:
    types: [submitted]
    branches: [ main ]


name: Transition Issue to "To Merge" State

jobs:
  call-workflow:
    uses: Veridise/.github/.github/workflows/jira-to-merge-transition-core.yml@main
    with:
      head-ref: ${{ github.event.pull_request.head.ref }}
    secrets: inherit
